name: Amazon Automation Test

on:
  push:
    branches:
      - main

jobs:
  playwright-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install playwright
          pip install pytest-html

      - name: Install Playwright Browsers & Dependencies
        run: |
          python -m playwright install --with-deps

      - name: Run Chromium Test
        run: pytest --browser chromium --html=report-chromium.html --self-contained-html

      - name: Run Firefox Test
        run: pytest --browser firefox --html=report-firefox.html --self-contained-html

      - name: Run WebKit Test
        run: pytest --browser webkit --html=report-webkit.html --self-contained-html