name: Playwright Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pytest playwright pytest-html
          python -m playwright install --with-deps

      - name: Run Chromium Test
        run: pytest --browser chromium --html=report-chromium.html --self-contained-html

      - name: Run Firefox Test
        run: pytest --browser firefox --html=report-firefox.html --self-contained-html

      - name: Run WebKit Test
        run: pytest --browser webkit --html=report-webkit.html --self-contained-html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            report-chromium.html
            report-firefox.html
            report-webkit.html